### ISSUE TITLE
如何运行您的例程呢？

### ISSUE THREAD

**Issue by ynu-zhangqiang** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#1]
同学你好，我是云大一枚小硕，一直在搞CNN算法的嵌入式移植，也是使用的Zedboard，想请教前辈如何运行您的例程？xilinx的工具都用的哪些？期待你的回复，谢谢！

**Comment by Yu-Zhewen** [comment]
你好，工具使用的HLS->Vivado->SDK. 系统在Tiny_YOLO_v3_ZYNQ/hw/yolo_sys_fp_prj_2019_64/

**Comment by ynu-zhangqiang** [comment]
好的好的，非常感谢你的回复，您所使用的的xilinx工具具体是哪一个版本呢？还有摄像头的版本是哪一款（包括摄像头的接口）？希望你能解答，感激不尽！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhewen Yu"<notifications@github.com&gt;; 
发送时间: 2019年11月16日(星期六) 晚上11:19
收件人: "Yu-Zhewen/Tiny_YOLO_v3_ZYNQ"<Tiny_YOLO_v3_ZYNQ@noreply.github.com&gt;; 
抄送: "1176265615"<1176265615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ] 如何运行您的例程呢？ (#1)




你好，工具使用的HLS-&gt;Vivado-&gt;SDK. 系统在Tiny_YOLO_v3_ZYNQ/hw/yolo_sys_fp_prj_2019_64/

**Comment by Yu-Zhewen** [comment]
2019.1 目前只做了网络本身的加速，并没有做接口

**Comment by software123123** [comment]
请问一下您所使用的是xilinx的哪一款开发板？

**Comment by Yu-Zhewen** [comment]
zedboard
