### ISSUE TITLE
Run model on different images

### ISSUE THREAD

**Issue by AramisOposich** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#10]
Hey,
you have provided a tool which converts an .png to .h file, but how an I change the input image for the classification?
And how can I print the yolo_output as an png file with bounding box?
I guess that your model don't run on mp4 files, is there any work around?

I really appreciate your work!

**Comment by Yu-Zhewen** [comment]
Hi, 

Currently, the only way to change the input image is to update the "group_0_input.h".

To generate the bbox,  please have a look at the original yolo implementation (For example, https://github.com/pjreddie/darknet/blob/master/src/yolo_layer.c#L83)

**Comment by giandras033235** [comment]
I read that pruning weights or filters leads to an sparser network. Is there any way to speed up the inferenze rate on the Zedboard?

**Comment by Yu-Zhewen** [comment]
Pruning definitely is a solution for further speed-up, but I am afraid it is not supported in this project.

**Comment by AramisOposich** [comment]
Interesting Question!

It would be also interesting to know if there could be a direct comparison of tiny Yolo and the Yolov3 in this implementation?
Since it is a zynq application to reconfigure a tiny and a yolo block.

**Comment by giandras033235** [comment]
> Pruning definitely is a solution for further speed-up, but I am afraid it is not supported in this project.

Do you mean by this that it is not possible with this project or that you have not implemented it (which would be clear)?
If not, could you help us which direction should we brainstorm for further speed up?

**Comment by Yu-Zhewen** [comment]
My understanding is that the main difference between YOLOv3, YOLOv3-tiny is the number of layers. Therefore, it is possible to support YOLOv3 by changing the configuration of IP blocks (start from https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/blob/d3d83d50a34378933b05b962c956e71654b390d8/code/sdk/src/yolo_sys.cpp#L549).

In terms of pruning, if it is channel pruning, then you also need to edit the file mentioned above, as the number of channels changes.  For unstructured pruning, it is not possible for this project unless you write your own HLS IP to support unstructured convolution computation.
