### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolo_yolo_prj/solution1/impl/ip/xilinx_com_hls_yolo_yolo_top_1_0.zip'

### ISSUE THREAD

**Issue by happyzhanglc** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#12]

**Comment by happyzhanglc** [comment]
when i run scripts/run_all.py on ubuntu16.04 , report above error, i cannot find "xilinx_com_hls_xxx" in the "xxx_prj/solution1/impl/ip" directory

**Comment by happyzhanglc** [comment]
my "yolo_yolo_prj/solution1/impl/ip" directory include :
.
├── autoimpl.log
├── auxiliary.xml
├── bd
├── constraints
├── doc
├── drivers
├── example
├── hdl
├── misc
├── pack.sh
├── run_ippack.tcl
├── subcore
├── vivado.jou
├── vivado.log
└── yolo_yolo_top_info.xml
cannot find "xilinx_com_hls_" + hls_prj_name

**Comment by happyzhanglc** [comment]
and in vivado_hls.log :
ERROR: [IMPL 213-28] Failed to generate IP.
command 'ap_source' returned error code
    while executing
"source run_hls.tcl"
    invoked from within
"hls::main run_hls.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 hls::main {*}$args"
    (procedure "hls_proc" line 5)
    invoked from within
"hls_proc $argv"
INFO: [HLS 200-112] Total elapsed time: 256.24 seconds; peak allocated memory: 425.257 MB.
INFO: [Common 17-206] Exiting vivado_hls at Sun Feb 20 17:20:45 2022...
occur above error.

**Comment by Yu-Zhewen** [comment]
seems to be a duplicate issue as #9

**Comment by happyzhanglc** [comment]
> seems to be a duplicate issue as #9
thanks, problem fixed.
