### ISSUE TITLE
Feeding images to the FPGA

### ISSUE THREAD

**Issue by TamarMos21** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#13]
Hello,
I have generated the IPs, block diagram and attempted to program the
hardware. I am having doubts what is the procedure and steps to set up the environment to feed images to the FPGA and get the classifications? Right now I have launched the SDK and trying to observe the signals. If you could direct me which software do I need and what steps should I take to test the design on images provided in the document?

Thank you

**Comment by Yu-Zhewen** [comment]
duplicate with #10 

To change the input, you need to load the image, convert the data to fixed point, transpose the image from 416\*416\*3 to 3\*416\*416, and pad the input from 3\*416\*416 to 4\*416\*416. Then copy the generated array into "code/sdk/include/group_0_input.h".

**Comment by TamarMos21** [comment]
Thank you for the response,

So first, we feed the image to tools\image_load\main.c, then we get the sized header file, which is floating-point  416*416*3, then do transpose (interleave) ?how to transpose?, then with tools\head_short\head_short.c quantize and then with tools\input_channel_pad\main.c do padding and get the final array
is this the procedure?

**Comment by Yu-Zhewen** [comment]
Let me clarify the procedure:
1. load the image using tools/image_load/main.c, and the image shall be the floating-point form of 3\*416\*416 (transpose has already been done within the same script)
2. quantise the image by modifying tools/head_short/head_short.c
3. pad the input from 3\*416\*416 to 4\*416\*416 with tools/input_channel_pad/main.c
