### ISSUE TITLE
请问如何将自己训练的模型参数变为工程中需要的格式呢？

### ISSUE THREAD

**Issue by Sunshine2019a** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#14]
余同学，您好！我在PYNQ-Z2(7020 clg400-1)开发板上复现了您开源的ZYNQ_YOLO_v3_tiny的工程，这个工程非常的优秀！但是我有一个困惑，我想向您请教一下如何把自己的训练的模型参数变为您的工程要求的导入的参数的格式，就像这样：https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/tree/master/data/layer_weight_bn_fp   。如果给您造成了打扰，我深感抱歉！

**Comment by Yu-Zhewen** [comment]
1. 将每一层的weight按照output_channel\*input_channel\*kernel_size的顺序存放在一维数组中。

2. 使用/tools/head_short 转换成定点格式。

3. 将kernel_size padding 成4的倍数, /tools/pad_weight。

4. 根据每一层的input_fold_factor，利用tools/interleave_weight_input将output_channel\*input_channel\*kernel_size转换成 input_fold_factor\*output_channel\*(input_channel/input_fold_factor)\*kernel_size。

5. 将获得的头文件替换code/sdk/include。

**Comment by Sunshine2019a** [comment]
好的，谢谢您的回复
