### ISSUE TITLE
SDK_Yolo_sys.cpp中 网络输出group_13.output和ref数据相减大于64，count计数+1？

### ISSUE THREAD

**Issue by qbbbbbb** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#15]
这个count是统计输出结果与参考数据相差的吗？应该最后输出等于零才对吗，我按照您的代码跑了一遍，将图片数据处理后放入group_0_input.h中，但是count最后累加到一个很大的值，我想知道这样是否正确。那个ref参考数据是怎么得到的呢

**Comment by Yu-Zhewen** [comment]
ref的数据是在没有FPGA加速时，network输出的结果。可以是将network在你的PC上运行或者只使用ZYNQ中的arm processor计算。

如果你改变了输入的图片，那ref当然也要相应的替换。可以将该图片用
https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/tree/1c629ad5592a63be0ec61391265feefe9e58068b/sw/desktop_ref
运行，之后再把输出的dat文件转换格式并替换"group_13_output.h"

**Comment by qbbbbbb** [comment]
好的，谢谢您的回复

**Comment by qbbbbbb** [comment]
您好，我按照您说的使用desktop_ref运行了并得到输出layer_output_sdk.dat,其输出是一些小数，将它输入到tools/dat_to_head中吗，但是dat_to_head代码是对整形数据进行处理的，感觉不太对，是我对生成的dat文件处理错误了吗？希望能够得到您的回答，这将对我帮助很大！

**Comment by Yu-Zhewen** [comment]
同学你好，我已经修改了上面的回答，建议使用desktop_fp_ref生成dat文件。desktop_fp_ref是quantise之后的模型而desktop_ref是f32的模型。之后，请按照以下步骤
1. tools/dat_fp_to_short将dat文件转换为short类型；
2. tools/dat_to_head将dat转换为.h；
3. tools/yolo_pad将26 \* 26 \* 255补零为26 \* 26 \* 256；
4. tools/interleave_output_group将数据转置
