### ISSUE TITLE
关于yolo_conv_top计算模块

### ISSUE THREAD

**Issue by sweetcatmiao** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#16]
您好，我尝试使用您的卷积计算模块时发现，虽然C仿真能够通过，但是使用C/RTL协同仿真时数据不对，并且上机后数据也有问题，但是当我取消了卷积模块的的PIPELINE优化指令后，虽然延时增加了，但是数据正确。并且资源也没有超载，请问是为什么呢？
我的版本是2018.3，芯片型号为xczu3eg-sfvc784-1-i。希望能得到您的回答。

**Comment by Yu-Zhewen** [comment]
请问您是使用提供的script自动生成的HLS project还是手动添加文件建立的

**Comment by sweetcatmiao** [comment]
我尝试过使用script的脚本来实现，只修改了芯片型号，也报错了，事实上，您的优化方案好像只能在zynq7000的系列上才能正常跑通，我尝试了Ultasale系列的很多都不行，换回7000系列的任意型号都行。感觉有点玄学。



在 2022-05-05 18:06:19，"Zhewen Yu" ***@***.***> 写道：

请问您是使用提供的script自动生成的HLS project还是手动添加文件建立的

**Comment by Yu-Zhewen** [comment]
在测试过程中，请问你是否手动或者用script修改过pipeline的II？
我觉得比较奇怪的一点是，根据你的描述，在不动代码的情况下，只是在HLS中修改target device， 就观察到了不同的仿真结果。是这样吗？

**Comment by sweetcatmiao** [comment]
不，我没有修改过任何代码，只是更改了target device，例如ultrascale 系列的xczu3eg-sfvc784-1-i，RTL仿真就会报错。

**Comment by sweetcatmiao** [comment]
是因为架构不同的原因吗？但我觉得也不应该出现这种问题才对。

**Comment by sweetcatmiao** [comment]
很感谢您能回复我，我已经解决啦，我看到了控制台关于linebuffer的错误依赖警告，尝试对您代码里的行缓冲器添加优化，例如：
#pragma HLS ARRAY_PARTITION variable=line_buff_group_0 complete dim=1，虽然警告依然存在，但能够跑通了。非常感谢您。
