### ISSUE TITLE
关于Block_Design的问题

### ISSUE THREAD

**Issue by erfqerfqerf** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#17]
您好，如何才能看到Block_Design中的IP连接方法，我想在Windows中建立工程。

**Comment by Yu-Zhewen** [comment]
同学你好，https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/tree/1c629ad5592a63be0ec61391265feefe9e58068b/hw/yolo_sys_fp_prj_2019_64 提供了完整的Vivado Project

**Comment by erfqerfqerf** [comment]
谢谢您问题解决了
