### ISSUE TITLE
在设计block design时，验证是否设计正确时遇到如下问题

### ISSUE THREAD

**Issue by zhangxianbin1999** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#18]
![IMG_20220827_154400](https://user-images.githubusercontent.com/104557952/187020632-60e9a05f-b011-4ddf-a3ab-8bd9b855e51a.jpg)

**Comment by Yu-Zhewen** [comment]
同学你好，请问你是用script生成的project吗

**Comment by zhangxianbin1999** [comment]
请问一下这个卷积神经网络加速模块能接摄像头么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ] 在设计block design时，验证是否设计正确时遇到如下问题 (Issue #18)




 
同学你好，请问你是用script生成的project吗

**Comment by Yu-Zhewen** [comment]
摄像头接口需要另外单独实现，目前的project并不包含
