### ISSUE TITLE
在执行脚本编译时，出现文件缺失的问题，这咋整

### ISSUE THREAD

**Issue by duoroudao** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#19]
![Ubuntu2004-64-2022-09-02-14-40-50](https://user-images.githubusercontent.com/92363966/188078421-bfe0ef50-0103-427d-8725-3bf470d4f7f2.png)

**Comment by Yu-Zhewen** [comment]
#9，看一下是不是同样的问题

**Comment by duoroudao** [comment]
谢谢(´▽`ʃ♡ƪ)




剁肉刀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yu-Zhewen/Tiny_YOLO_v3_ZYNQ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ] 在执行脚本编译时，出现文件缺失的问题，这咋整 (Issue #19)





 
#9，看一下是不是同样的问题
