### ISSUE TITLE
有些问题想请教您

### ISSUE THREAD

**Issue by baishanca** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#2]
博主您好，主要还是FPGA小白一个，不然也不会麻烦您。算法都懂，您能简单讲一下您这个工程在FPGA上的实现流程吗（就是怎么操作。。。（捂脸）），谢谢您了，板子是zynq7100

**Comment by Yu-Zhewen** [comment]
就是常规的HLS->Vivado->SDK, 参考 Xilinx UG871和UG902

**Comment by baishanca** [comment]
博主，现在想把您的项目在zynq7100上复现，您定义的IP不知道该怎么去修改，还有一些其他问题想请教你，有偿的，不知道该怎么联系您
