### ISSUE TITLE
量化方法

### ISSUE THREAD

**Issue by erfqerfqerf** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#20]
请问一下，神经网路参数以及输入输出数据的量化方法是什么

**Comment by Yu-Zhewen** [comment]
都是量化为16位，https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/blob/6916290b188626a2455fb8552b5130b5fa6513f7/code/hls/yolo_acc/src/yolo_fp.h#L6-L7
