### ISSUE TITLE
激活函数

### ISSUE THREAD

**Issue by erfqerfqerf** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#21]
您的工程中，怎么处理的silu激活函数

**Comment by Yu-Zhewen** [comment]
yolov3没有使用SiLU作为激活函数，只在输出部分用到了Sigmoid
https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/blob/6916290b188626a2455fb8552b5130b5fa6513f7/code/hls/yolo_yolo/src/yolo_yolo.cpp#L74-L80
