### ISSUE TITLE
Procedure to extract weight of individual layers and weight loss function

### ISSUE THREAD

**Issue by Sridhar-ubq** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#22]
Hello,

I was redirected to this repo from your original work w.r.t yolov3-tiny on zedboard.  I appreciate the work you have done. But I have some questions. 

1. How did you manage to extract the weights of individual layers to be given at the compile time?  Did you use google collab or something else to extract the weights of individual layer.  ? 

2. I think you are using weight loss function to calculate the % weight loss for a given fixed point format. How does weight loss function directly related to accuracy? I know this is a theoretical question but I'm relatively new to this field. I would highly appreciate if you can briefly answer this or direct me to any literature that answers this.

**Comment by Yu-Zhewen** [comment]
There is no training involved in this project. The weight file is directly taken from [pjreddie.com/media/files/yolov3-
tiny.weights](url).

In general, the weight loss (normalised mean square error) metric defined in our paper provides a rough estimation of the quantisation error.  This metric is widely used in previous papers such as [https://arxiv.org/pdf/1901.09504.pdf](url), [https://arxiv.org/pdf/1810.05723.pdf](url). It is difficult to say if it is a good indicator of accuracy, especially when the error accumulates in a deep network.

**Comment by Sridhar-ubq** [comment]
Thank you Yu for your response.  

I still have a query regarding the first question.  Yolov3-tiny.weight file is an executable file. In your project, you have extracted weight layer-by-layer when running the software desktop version from this executable file. How did you manage to do that? Is there a script that does it.? Thank you for your response. Really appreciate your effort.

**Comment by Yu-Zhewen** [comment]
You can modify the weight parser to achieve that [(https://github.com/pjreddie/darknet/blob/a3714d0a2bf92c3dea84c4bea65b2b0c64dbc6b1/src/parser.c)](url)
