### ISSUE TITLE
How to do the detection in PS

### ISSUE THREAD

**Issue by Sridhar-ubq** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#23]
Hello Yu,

I wanted to know how to perform the detections in the PS part.  The SDK code generates group_13.output as yolo output. This output is compared with the post-processed output of the fixed point version.  I wanted to use the output of group_13.out and group_10.output for generating the predictions. 

I'm using the method you provided in Readme (given below) but in a reverse fashion to generate the floating point data for prediction but this does not work. 
Use tools/dat_fp_to_short to convert the datatype to short
Use tools/dat_to_head to convert the dat file into a header file
Pad the reference output from 26*26*255 to 26*26*256, by tools/yolo_pad
Transpose the output by tools/interleave_output_group.

Can you give some hints regarding how to post-process group_13.output.h and group_10.output.h for generating predictions? 

Additionally, I'm trying to use the desktop_fp_ref version to create ref output but I'm getting an error 

./src/activations.h: In function ‘fp_data_type logistic_activate(fp_data_type)’:
../src/activations.h:13:129: error: call of overloaded ‘exp(ap_fixed_base<17, 9, true, (ap_q_mode)5, (ap_o_mode)3, 0>)’ is ambiguous
 static inline fp_data_type logistic_activate( fp_data_type x){return (fp_data_type)1./((fp_data_type)1. + (fp_data_type)exp(-(x)));}

I can surpass this error by converting x to float before taking the exponent but it is creating a difference in your ref out (group_13_output.h) and the one with my fix.  Did you face the same error?  I'm looking forward to your reply. Thank you

**Comment by bo102** [comment]
Hello, when I reproduced your project, the board was implemented as AX7020.But there was no result when it was finally implemented, do you know what is going on? Thank you very much!
![image](https://user-images.githubusercontent.com/131770424/234267203-c2671c47-c86f-4768-99a5-5e44655ccb04.png)

**Comment by zhouweic36** [comment]
我的也是一样，一直停在这里不动

**Comment by zhouweic36** [comment]
增加 ld文件里的分配空间，可出结果 ，但利用yolo层得到坐标和得到PS中的Head文件有些问题，还有其它资料可以参考下吗？
