### ISSUE TITLE
训练自己数据

### ISSUE THREAD

**Issue by fys-leo** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#24]
大佬，如果训练自己的数据在fpga实现怎么做呢

**Comment by bo102** [comment]
> 大佬，如果训练自己的数据在fpga实现怎么做呢

哥，你在板子上成功复现了他的项目了吗？我在ax7020板子上，没有输出结果？[](url)

**Comment by bo102** [comment]
![image](https://user-images.githubusercontent.com/131770424/234267346-c847ba59-3a27-470a-a06c-a5685a82707d.png)

**Comment by zhouweic36** [comment]
好像是卡在了  DMA    这里是不是数据 没有传输成功？

**Comment by bo102** [comment]
> 好像是卡在了 DMA 这里是不是数据 没有传输成功？

请问有什么办法可以解决吗？

**Comment by Yu-Zhewen** [comment]
> 大佬，如果训练自己的数据在fpga实现怎么做呢

可以参考 #14 的步骤
