### ISSUE TITLE
Steps to build the environment

### ISSUE THREAD

**Issue by aalito** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#25]
Hi, 

I have no experience in using Vivado, and I don't from where to start.

So, would you please elaborate more on how to use the automated flow using ubuntu 16.04 LTS, Vivado v2019.1, python 3.5.2, gcc 5.4.0. 

I have vivado 2014.2 on Windows, so, could you please share a high level steps to deploy the design example on Zedboard ?

Please advise.

**Comment by Yu-Zhewen** [comment]
Hi, you can either use the provided script “scripts/run_all.py”, or do everything manually. The design follows a standard process from HLS, Vivado and to SDK, which is elaborated in Xilinx documents  UG871 and UG902
