### ISSUE TITLE
Problem with HLS Synthesis step.

### ISSUE THREAD

**Issue by thomasjeff0420** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#26]
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/04773a1b-2162-472a-b974-f38fc47150de)
When I tried to re-compile your source. I encounter this error which prevent to create an IP. Could you please give me any idea to get rid of this situation.

**Comment by Yu-Zhewen** [comment]
Hi, from the screenshot you provide, it only contains some warnings, which shouldn’t prevent you from generating the IP. Is there any other specific error message you see, and is it failing during C synthesis or exporting IP?

**Comment by thomasjeff0420** [comment]
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/c159faef-f1b3-40c3-be0d-b745f1497b71)
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/cafb9511-b986-4f4c-9120-0e2b831437bb)
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/ef663eae-1526-439e-913c-f65307e56814)
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/3462afae-81dc-40ff-94ca-1615b0ca99d3)
![ảnh](https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/assets/134514490/02546f31-36e7-4b5a-b623-55a6c99ed91a)
In facts, those warning prevent me from creating the IP core. When I clicked on the warning, this led me to the line as shown in the second picture. This warning appear in all of 4 module. When I tried to decrease the MAX_KERNEL_NUM to 3 [picture number 3], then "store" and "load" warning vanish, but the array "kernel bias" still can not be allocated.  But I believe it would damage the architecture of system. Also, I still doubt about why you define MAX_CH_BIT as ( 5+1 ) instead of (6) and MAX_FOLD_CH_BIT as (5-2+1 ) instead of 4 or a variable? Could you please explain it to me? Thanks you so much.

**Comment by thomasjeff0420** [comment]
> Hi, from the screenshot you provide, it only contains some warnings, which shouldn’t prevent you from generating the IP. Is there any other specific error message you see, and is it failing during C synthesis or exporting IP?

No, C synthesis successfully done without any errors,

**Comment by thomasjeff0420** [comment]
And I'm planning to test my custom model on your project to have a result in order to compire with my project. Can I do that? If yes, Which parts of your code should be modify. Could you guide me? Thanks you.

**Comment by Yu-Zhewen** [comment]
> > Hi, from the screenshot you provide, it only contains some warnings, which shouldn’t prevent you from generating the IP. Is there any other specific error message you see, and is it failing during C synthesis or exporting IP?
> 
> No, C synthesis successfully done without any errors,

if you can pass C synthesis, then it's very unlikely the warning is the issue. could you have a look at what message is shown in the console tab?

**Comment by Yu-Zhewen** [comment]
Also, I wonder if it is relevant to #9

**Comment by thomasjeff0420** [comment]
Thanks for your help, It worked!. Also, Can I deploy my custom model to your project?. My custom model use YOLOv3 tiny and I just want to have the result to do a compare with my own system. If yes, could you show me where I should modify in order to make it work. Since I see the YOLO weight and config file was separated from your main system design. I believe that I could replace it with my own model. Thanks you.

**Comment by Yu-Zhewen** [comment]
if you wanna modify the weights, you can take the following steps:

1. Store the weight of each layer in the one-dimensional array in the order of output_channel\*input_channel\*kernel_size.

2. Use /tools/head_short to convert weights to fixed-point format.

3. Set kernel_size padding to a multiple of 4, using /tools/pad_weight.

4. Use tools/interleave_weight_input to convert output_channel\*input_channel\*kernel_size into input_fold_factor\*output_channel\*(input_channel/input_fold_factor)\*kernel_size.

5. Use the obtained header files to replace code/sdk/include.
