### ISSUE TITLE
yolo0-yolo1输出维度，后处理交流和zynq7045，ZCU102移植问题

### ISSUE THREAD

**Issue by yxandam** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#5]
您好：
首先非常感谢您愿意把自己的工作开源出来，我详细阅读了您的代码，目前已经在7045上复现了您的工程，但是有一些问题想再次请教一下。
1：yolo0与yolo1 的输出维度问题，在论文里面您写的分别是255*13*13和255*26*26，但是在具体的代码实现过程中，您的输出是256*13*13和256*26*26，是不是为了凑整，多余的一个维度不影响精度对吧？
2：后处理的部分，您没有在工程里描述，这部分可以提供点线索吗？利用yolov3-tiny的后处理怎么衔接呢？
3：如果我往ZCU102这样资源比较多的板子上移植，有什么简单的优化策略呢？
希望您能在百忙之中抽空解答一下疑问，不胜感激。
谢谢

**Comment by guoke12321** [comment]
您好，我也想学习一下这个工程，但无奈屡次下载不能成功，请问您方便把工程发我一份吗？邮箱：1432880127@qq.com,不胜感谢。

**Comment by guoke12321** [comment]
你好，我也正做这个项目的复现，但在sdk输出打印时，显示一些ip核驱动函数的初始化后就停止了，请问你的复现结果如何？

**Comment by guoke12321** [comment]
你好，我也正做这个项目的复现，但在sdk输出打印时，显示一些ip核驱动函数的初始化后就停止了，请问你的复现结果如何？

**Comment by Yu-Zhewen** [comment]
你好，

抱歉过了那么久才回复

1. 255,256是为了凑整，不影响精度
2. 后处理（nms和画框）目前都是在PS,可以考虑移植到PL
3. 一般主流的stream结构会给每个layer分配一个单独的IP（而不是每一种layer type分配一个), 可以实现layer level 的并行，同时减少dma 开销； 另外就是preload weight

**Comment by yxandam** [comment]
非常感谢您的回复，也看到了您新的资料，我这边再试试。
