### ISSUE TITLE
I don't

### ISSUE THREAD

**Issue by zhanghb1915** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#6]

**Comment by zhanghb1915** [comment]
I would like to know whether the result I get is the output of YOLO layer. Do these two outputs need NMS to produce detection pictures? And I don't kown why the size of group_0_input.h is 416x416x4 instead of 416x416x3

**Comment by Yu-Zhewen** [comment]
Yes, the results are just yolo layers and you need NMS. 

The input is padded from 416x416x3 to 416x416x4 because our IPs always process 4 channels in parallel.

**Comment by guoke12321** [comment]
Hi，I don't know why the convolution module needs 144 DSPS. From the cpp code, I only found 9 times of parallelism in the convolution kernel and 4 times of parallelism in the input channel. Is there a parallel strategy for the output channel? thanks

**Comment by Yu-Zhewen** [comment]
There is a parallel strategy among output channels. How many output channels in parallel is mostly related to the design parameter P_{mem} (L39 of "code/hls/yolo_conv/src/yolo_conv.cpp"). That's how our design becomes tuneable. For more details, please have a look at the paper or the report.
