### ISSUE TITLE
关于DSE中，OITR_range以及OP_lim参数问题

### ISSUE THREAD

**Issue by zhouzj01** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#7]
您好，在您设计DSE探索时，main.cpp里关于OITR_range=[1,2,3,4]以及OP_lim=6的取值是怎么来的呢？我想了好久，一直不能理解，也未能在您文中找到具体说明。麻烦您能指点一下吗？不胜感激！

**Comment by Yu-Zhewen** [comment]
OP_lim的取值是在HLS综合后观察得到的。OITR_range实际上是Conv Layer 的output feature maps和 input feature maps的比值。对于yolov3-tiny， 最大的比值出现在第一层Conv 16/3 (近似为4)。

**Comment by zhouzj01** [comment]
非常感谢您的解答!对于求取卷积的BRAM时，分为12组，每组包含「Nmax/8」，8是怎么理解呢？为什么不是用每组包含的数据418*Nmax/4，再除上一个BRAM_18K所能容纳的数据1024个，即（418*Nmax）/（4*1024）？希望您能回复，谢谢！

**Comment by Yu-Zhewen** [comment]
Q: 对于求取卷积的BRAM时，分为12组，每组包含「Nmax/8」，8是怎么理解呢？为什么不是用每组包含的数据418Nmax/4，再除上一个BRAM_18K所能容纳的数据1024个，即（418Nmax）/（4*1024）？

A: 这里将418近似为512
